version: '3'
services:
  web:
    image: osiolabs/drupaldevwithdocker-php
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html:cached
  db:
    image: osiolabs/drupaldevwithdocker-mysql
    ports:
      - "3316:3306"
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    env_file:
      - ./docker.env
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - ./docker.env